---
  - block:
    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: 0700
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"
