---
  - name: empty handler
    become_user: "{{ansible_user}}"
    shell: |
      echo 'doing nothing'

  - name: restrict interfaces
    #need to be run as domain-user
    #become_user: domain-user
    become: yes
    become_user: "{{ansible_user}}" #set in role defaults
    shell:
      'dbus-launch gsettings set org.gnome.Vino network-interface lo'

  - name: create vino launcher
    copy:
      src: /var/lib/awx/projects/astra_linux_se/shared/vino-server.desktop
      dest: "{{ansible_user_dir}}/Desktops/Desktop1"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0644

  - name: ensure winbind domain user/group query is disabled
    become: yes
    lineinfile:
      dest: /etc/samba/smb.conf
      state: present
      regexp: "{{item.regexp}}"
      line: "{{item.line}}"
    with_items:
    - {regexp: '^winbind enum users*', line: "winbind enum users = no" }
    - {regexp: '^winbind enum groups*', line: "winbind enum groups = no" }
    - {regexp: '^idmap config \* : range = ', line: "idmap config * : range = 10000-20000" }

  - name: edit existing line in pam_mount conf-file
    become: yes
    lineinfile:
      dest: /etc/security/pam_mount.conf.xml
      state: present
      line: "{{item.line}}"
      regexp: "{{item.regexp}}"
    with_items:
    - { line: <logout wait="500000" hup="1" term="1" kill="1" />, regexp: '^<logout*'}
    - { line: <mkmountpoint enable="1" remove="false" />, regexp: '^<mkmountpoint*'}

  - name: add block-conf to pam_mount conf-file
    become: yes
    blockinfile:
      dest: /etc/security/pam_mount.conf.xml
      block: |
        <cifsmount>mount.cifs //%(SERVER)/%(VOLUME) %(MNTPT) -o %(OPTIONS)</cifsmount>
        <volume fstype="cifs" server="{{shared_storage_ip}}" path="{{shared_storage_path}}" mountpoint="~/Общедоступные" options="user=%(USER),rw,setuids,perm,soft,iocharset=utf8,uid=%(USERUID),gid=%(USERGID)" />
      insertbefore: '</pam_mount>'

  - name: add network storage address to /etc/hosts
    become: yes
    lineinfile:
      dest: /etc/hosts
      state: present
      line: "{{shared_storage_ip}}\t{{shared_storage_fullname}}\t{{shared_storage_shortname}}"
      insertafter: '^127.0.1.1*'

  - name: restart network
    become: yes
    shell: service networking restart
    args:
      warn: false

  - name: restart NetworkManager
    systemd:
      state: restarted
      name: NetworkManager

  - name: remember NetworkManager connection type
    shell: cat /etc/NetworkManager/system-connections/* | grep type | sed 's/type=//'
    #shell: nmcli con show -a | awk -F',' 'NR == 4 { print $5 }'
    register: type

  - name: remember NetworkManager connection ifname
    shell: nmcli con show -a | awk -F',' 'NR == 4 { print $6 }'
    register: ifname

  - name: remove all NetworkManager connections
    shell: rm -rf /etc/NetworkManager/system-connections/*

  - name: deploy freeipa client
    shell: "astra-freeipa-client -d {{domain}} -u {{freeipa_admin_user}} -y"
